# Generated by Django 2.0.6 on 2018-06-25 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='ExchangeResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField()),
                ('success', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(max_length=5000)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recruiting.Company')),
                ('locations', models.ManyToManyField(blank=True, to='recruiting.City')),
            ],
            options={
                'verbose_name_plural': 'Vacancies',
            },
        ),
        migrations.AddField(
            model_name='exchangeresult',
            name='screenshot_list',
            field=models.ManyToManyField(to='recruiting.Image'),
        ),
        migrations.AddField(
            model_name='exchangeresult',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiting.Vacancy'),
        ),
    ]
