# Generated by Django 2.0.6 on 2018-06-28 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0003_auto_20180627_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeresult',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
