# Generated by Django 2.0.6 on 2018-06-29 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0004_auto_20180628_0716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screenshot',
            name='screen_name',
        ),
    ]
