# Generated by Django 2.0.6 on 2018-07-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0005_remove_screenshot_screen_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeresult',
            name='screenshot_list',
            field=models.ManyToManyField(blank=True, to='recruiting.Screenshot'),
        ),
    ]
